In [57]:
import pandas as pd
import numpy as np
import dataPro

In [48]:
path = r"./data/sh.600000.csv"
data = pd.read_csv(path)

In [58]:
dataPro.getShiftData(path,2,3)

([array([ 0.        ,  0.        ,  0.        ,  0.00116686,  0.        ,
         -0.00117233,  0.        ,  0.00468933,  0.        ,  0.644495  ,
          0.        ,  0.6453265 ]),
  array([0.        , 0.00351288, 0.        , 0.01165501, 0.        ,
         0.00469484, 0.        , 0.00816803, 0.        , 0.47076626,
         0.        , 0.47003891]),
  array([ 0.        ,  0.01050175,  0.        , -0.00230415,  0.        ,
          0.        ,  0.        , -0.00810185,  0.        , -0.26015683,
          0.        , -0.25992589]),
  array([ 0.        , -0.01039261,  0.        ,  0.00808314,  0.        ,
          0.00116822,  0.        ,  0.01633606,  0.        ,  0.53586805,
          0.        ,  0.53576538]),
  array([ 0.        ,  0.01750292,  0.        ,  0.00572738,  0.        ,
          0.01050175,  0.        ,  0.00114811,  0.        , -0.45959644,
          0.        , -0.45971122]),
  array([0.        , 0.00229358, 0.        , 0.        , 0.        ,
         0.0034642

In [49]:
data

Unnamed: 0        date       code  open  high   low  close  preclose  \
0             0  2021-12-31  sh.600000  8.54  8.57  8.53   8.53      8.54   
1             1  2022-01-04  sh.600000  8.54  8.58  8.52   8.57      8.53   
2             2  2022-01-05  sh.600000  8.57  8.68  8.56   8.64      8.57   
3             3  2022-01-06  sh.600000  8.66  8.66  8.56   8.57      8.64   
4             4  2022-01-07  sh.600000  8.57  8.73  8.57   8.71      8.57   
..          ...         ...        ...   ...   ...   ...    ...       ...   
233         233  2022-12-19  sh.600000  7.37  7.37  7.21   7.24      7.35   
234         234  2022-12-20  sh.600000  7.23  7.28  7.13   7.14      7.24   
235         235  2022-12-21  sh.600000  7.22  7.24  7.13   7.19      7.14   
236         236  2022-12-22  sh.600000  7.28  7.31  7.20   7.24      7.19   
237         237  2022-12-23  sh.600000  7.19  7.27  7.17   7.19      7.24   

       volume        amount  adjustflag    turn  tradestatus  pctChg  isST  
0    22929621  1.959416e+08           3  0.0781            1 -0.1171     0  
1    37707647  3.221455e+08           3  0.1285            1  0.4689     0  
2    55459135  4.788345e+08           3  0.1889            1  0.8168     0  
3    41031062  3.527207e+08           3  0.1398            1 -0.8102     0  
4    63018297  5.464562e+08           3  0.2147            1  1.6336     0  
..        ...           ...         ...     ...          ...     ...   ...  
233  20432546  1.485762e+08           3  0.0696            1 -1.4966     0  
234  24800259  1.783697e+08           3  0.0845            1 -1.3812     0  
235  17252934  1.242092e+08           3  0.0588            1  0.7003     0  
236  18662641  1.355090e+08           3  0.0636            1  0.6954     0  
237  12958464  9.346305e+07           3  0.0441            1 -0.6906     0  

[238 rows x 15 columns]

In [50]:
i = 0
preDays = 5
(data["open"][i:i+preDays] - data["open"][i] ) / data["open"][i]

0    0.000000
1    0.000000
2    0.003513
3    0.014052
4    0.003513
Name: open, dtype: float64

In [51]:
feat = lambda item: data[item][i:i+preDays] - data[item][i]
feat("open")

0    0.00
1    0.00
2    0.03
3    0.12
4    0.03
Name: open, dtype: float64

In [52]:
x_i = [feat("open"),feat("high"),feat("low"),feat("close"),feat("volume"),feat("turn")]

In [53]:
np.array(x_i)

array([[ 0.0000000e+00,  0.0000000e+00,  3.0000000e-02,  1.2000000e-01,
         3.0000000e-02],
       [ 0.0000000e+00,  1.0000000e-02,  1.1000000e-01,  9.0000000e-02,
         1.6000000e-01],
       [ 0.0000000e+00, -1.0000000e-02,  3.0000000e-02,  3.0000000e-02,
         4.0000000e-02],
       [ 0.0000000e+00,  4.0000000e-02,  1.1000000e-01,  4.0000000e-02,
         1.8000000e-01],
       [ 0.0000000e+00,  1.4778026e+07,  3.2529514e+07,  1.8101441e+07,
         4.0088676e+07],
       [ 0.0000000e+00,  5.0400000e-02,  1.1080000e-01,  6.1700000e-02,
         1.3660000e-01]])

In [54]:
x_i
arr = np.array(x_i)



In [60]:
arr2 = arr.reshape(1,30)
arr2.shape

(1, 30)

In [61]:
arr2

array([[ 0.0000000e+00,  0.0000000e+00,  3.0000000e-02,  1.2000000e-01,
         3.0000000e-02,  0.0000000e+00,  1.0000000e-02,  1.1000000e-01,
         9.0000000e-02,  1.6000000e-01,  0.0000000e+00, -1.0000000e-02,
         3.0000000e-02,  3.0000000e-02,  4.0000000e-02,  0.0000000e+00,
         4.0000000e-02,  1.1000000e-01,  4.0000000e-02,  1.8000000e-01,
         0.0000000e+00,  1.4778026e+07,  3.2529514e+07,  1.8101441e+07,
         4.0088676e+07,  0.0000000e+00,  5.0400000e-02,  1.1080000e-01,
         6.1700000e-02,  1.3660000e-01]])